## The file contains hiring statistics for a company such as experience of candidate,  test score and interview score, based on these parameters HR has to decide the  salary. Build machine learning model for HR department that helps to decide the salaries for the future candidates.

In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import math

ModuleNotFoundError: No module named 'word2number'

In [6]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5586 sha256=d4f308ac9560ae484724d4a0d752099e12421cbcdb74a9f3866e67da79642d08
  Stored in directory: c:\users\monisha\appdata\local\pip\cache\wheels\cb\f3\5a\d88198fdeb46781ddd7e7f2653061af83e7adb2a076d8886d6
Successfully built word2number


In [8]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n
import math
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
df.experience=df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [10]:
df.experience= df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [15]:
med=math.ceil(df['test_score(out of 10)'].median())
med

8

In [16]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(med)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [17]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [18]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [21]:
reg.intercept_

17737.26346433771

In [22]:
reg.predict([[4,6,5]])

array([51089.51965066])

In [23]:
2812.95487627*4+1845.70596798*6+2205.24017467*5+17737.26346433771

51089.51965064771

In [24]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [25]:
2812.95487627*12+1845.70596798*10+2205.24017467*10+17737.26346433771

92002.1834060777